### ISSUE TITLE
Ability to adjust channel levels to mix buses

### ISSUE THREAD

**Issue by staljabro** [wrodie/ha_behringer_mixer#21]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/wrodie/ha_behringer_mixer/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

It works well for me, however my use case is using the X32 as a zone mixer, sometimes with multiple signals being sent to different zones (buses or matrices)

### Describe the solution you'd like

The ability to adjust levels per channel as sends to buses. (for example, being able to adjust the level of channel 1 in mix bus 3, etc.)

### Describe alternatives you've considered

Could potentially live with just turning channels on/off to the buses, but volume controls would be better

### Additional context

Is there a way to implement this, and in the initial config have the ability to select the channels and buses you wish to control, to reduce clutter. (For instance, only have HA listen to the first 8 channels and 6 buses. Ignore all the others)

**Comment by wrodie** [comment]
So the way you would see this is you would want the fader to represent the send from a  particular channel to a specific bus?
So for the X32 with 16 mix busses that would be another 32x16 =512 faders (plus 512 mutes plus 512 level sensors) . Another 1536 extra entities.

Would you want to control bus -> matrix sends as well ; an additional 96 faders (total 288 entities). 

While it seems like it would work conceptually, that is a lot of extra clutter. I think the trick would come down to how you would configure it.  Adding an extra 1834 entities by default seems excessive.

I think you'd have to have some setup options to turn on/off functionality.
As an example how would you want to configure it?

**Comment by wrodie** [comment]
I've just released v0.1.4 which should support this functionality.
You will need to create a new instance for the integration for it to work.  
When setting it up you are asked which channels etc you want to import and whether you want sends.

**Comment by staljabro** [comment]
Thanks wrodie! Works wonderfully!
