### ISSUE TITLE
Ability to control the USB recorder on the mixer

### ISSUE THREAD

**Issue by manrajsingh** [wrodie/ha_behringer_mixer#23]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/wrodie/ha_behringer_mixer/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not related to a problem.

### Describe the solution you'd like

It would be nice to have the ability to control the on board USB recorder with Home Assistant.

### Describe alternatives you've considered

I have not considered or know of any alternative.

### Additional context

We upgraded to x32 Rack digital mixer and put it in a locked rack cabinet (because some users  don't know what they are doing) and only provided On/Off switches for the users to turn on/off mixer and amps. With the help of this _godsend_ of an integration, we are also able to let users load "scenes" from the mixer on a tablet running home assistant app. Scene switching takes care of fader levels and muting/un-muting of channels & buses etc without giving them full access to x32edit.

The need of recorder controls in home assistant app arises when we need to record audio on a USB on special occasions. The idea is that x32 Rack mixer stays locked away from people who don't know what they are doing while giving them very minimal set of controls through home assistant.

**Comment by wrodie** [comment]
I'm glad you find the integration useful.  I also have a mixer card (https://github.com/wrodie/mixer-card) for HA Dashboards to control faders/mutes that might be useful to give your users the ability to change faders easily within HA.

In terms of what you are looking for with the USB recorder, would it purely be start/stop recording? or do you need to play back etc.

**Comment by manrajsingh** [comment]
Purely to start / stop recordings. I can't think of a use-case to play/pause recordings from home assistant at the moment. It would be icing on the cake if there was an indicator to know when it is safe to pull the USB out.

**Comment by wrodie** [comment]
It doesn't look like the Behringer API supports any kind of notification on when the USB is safe to remove.

**Comment by manrajsingh** [comment]
meh that's ok, I guess users can be trained to not unplug the USB stick while USB indicator is lit.

**Comment by wrodie** [comment]
I've just released a new version that has a couple of new features
1. You can now see the current USB filename being recorded to
2. The 'tape' status field. This shows the current status of the recorder.  This is a select element that can then be changed to RECORD, STOP etc.

Hopefully this works for you, let me know if it doesn't.
