### ISSUE TITLE
Script Error after recent HA update

### ISSUE THREAD

**Issue by darranwil** [wrodie/ha_behringer_mixer#66]
## System Information

version | core-2024.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.34.0
Stage | running
Available Repositories | 1460
Downloaded Repositories | 26
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | October 20, 2024 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-5.ui.nabu.casa
certificate_status | ready
instance_id | 3446003e0ddd49da990051b6e33da370
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 11.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), ESPHome (2024.7.3), Spotify Connect (0.13.0), TasmoAdmin (0.30.4), Terminal & SSH (9.14.0), File editor (5.8.0), Network UPS Tools (0.13.1), UniFi Network Application (3.2.0), TasmoBackup (1.06.06), Samba Backup (5.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 11
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 8, 2024 at 7:30 PM
-- | --
current_recorder_run | August 18, 2024 at 3:39 AM
estimated_db_size | 121.47 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/wrodie/ha_behringer_mixer/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Recently installed the integeratration to work with a Midas MR18. Has been working great! Love it! But after recent HA update I am getting this error. It appears to still be sending commands from HA to the mixer but the HA buttons are not changing color to show state.

The script "Send Mixer Command1" (script.send_mixer_command1) is not active because the configuration has errors.

Error:extra keys not allowed @ data['sequence'][0]['address']. Got '192.168.1.100' extra keys not allowed @ data['sequence'][0]['message']. Got {'address': '/channel/01/mix/fader', 'arguments': [0.75]} extra keys not allowed @ data['sequence'][0]['port']. Got 10024 template value is None for dictionary value @ data['sequence'][0]['data']. Got None.

### Reproduction steps

1. Unknown
2.
3.
...

### Debug logs

```text
Logger: homeassistant.components.script
Source: components/script/config.py:147
integration: Script (documentation, issues)
First occurred: 3:40:34 AM (1 occurrences)
Last logged: 3:40:34 AM
Script with alias 'Send Mixer Command1' could not be validated and has been disabled: extra keys not allowed @ data['sequence'][0]['address']. Got '192.168.1.100' extra keys not allowed @ data['sequence'][0]['message']. Got {'address': '/channel/01/mix/fader', 'arguments': [0.75]} extra keys not allowed @ data['sequence'][0]['port']. Got 10024 template value is None for dictionary value @ data['sequence'][0]['data']. Got None
```

**Comment by wrodie** [comment]
I don't have an MR18 I can test with at the moment, but it seems to work with the X32 in the latest version of HA.
Can you give me some idea of how you set this up and what you are doing when this error occurs?
