### ISSUE TITLE
Request to add M/C Fader from Behringer x32

### ISSUE THREAD

**Issue by sjbcpubrel3840** [wrodie/ha_behringer_mixer#67]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/wrodie/ha_behringer_mixer/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I do not consider this a problem just an improvement.

### Describe the solution you'd like

I would like to see Mono Center (M/C) fader to the list of faders that can be controlled. I apologize if that is already available, but I did not see this in the list of entities that can be controlled. 

### Describe alternatives you've considered

I can control all other faders that I need including main, but would like to see M/C controlled as well.

### Additional context

![Capture](https://github.com/user-attachments/assets/178a4677-6165-4614-9bc7-c2c3bc3eb065)

**Comment by wrodie** [comment]
I've just released a version that should make a 'Mono' channel available.
Let me know if you have any problems with it.

**Comment by sjbcpubrel3840** [comment]
Thank you for adding the Mono Fader. It works well!
